### ISSUE TITLE
Sce_sys files ? 

### ISSUE THREAD

**Issue by Hyndrid** [idlesauce/ps4-eboot-dlc-patcher#10]
Several dlcs only need the sce_sys files and DLC Patcher does not extract the files.

**Comment by idlesauce** [comment]
Do you mean there are dlcs that are marked as with extra data that arent getting extracted? Can you give an example?

**Comment by idlesauce** [comment]
Talked in dms, dlcs were without data, so nothing extracted is expected behaviour.
