### ISSUE TITLE
CTR Crash Team Racing ISSUE

### ISSUE THREAD

**Issue by devi691** [idlesauce/ps4-eboot-dlc-patcher#11]
CTR Crash Team Racing elf not generating ' dlcldr.prx  '.

**Comment by devi691** [comment]
Dragon Ball Xenoverse 2 elf not generating ' dlcldr.prx '.

**Comment by idlesauce** [comment]
I looked at both of these games, and both need fallback to in-executable handling, you should have gotten a confirm "dialog" about this, so this is expected behaviour. Ill try to make the readme more clear about this for the next release. Did you test the patched executables?
