### ISSUE TITLE
Limit DLC that can be added. (limited strings)

### ISSUE THREAD

**Issue by AndreaNorth98** [idlesauce/ps4-eboot-dlc-patcher#4]
after each string inserted, having reached approximately 10 strings inserted (line:10), once started it returns an error, which does not happen if the number of strings is decreased (the same strings but reduced to 5, 6), it does not generate a error and it works.

Is it possible to remove this limit if there are no technical problems?

otherwise you can't use games that contain a lot of DLC (especially those without extra data), perhaps even just by increasing this limit?

Thank you for all your work and support.

**Comment by idlesauce** [comment]
The latest version, with the new method can store 2500 dlcs (this is an arbitrary limit, but its from the official sdk), give it a shot, compatibility is still not perfect but most likely itll work
