### ISSUE TITLE
issue activation 2 dlc type dlc with data +dlc without data

### ISSUE THREAD

**Issue by Speed0780** [idlesauce/ps4-eboot-dlc-patcher#5]
Hi

**there is issue when try activate 
dlc with data + dlc without data in same time and build package after build and install game will be crash when launch on ps5

like call of duty  have  dlc with data and dlc without data  and try activate both game will be crash when launch on ps5
so when try  activate only dlc with data game its work or  activate dlc without data also work 
but if try activate both dlc with data + dlc without data  game will be crash when launch on ps5**

**Comment by idlesauce** [comment]
I think the issue was with the number of dlcs, not that it was different types, but regardless the latest version will probably work.

**Comment by Speed0780** [comment]
thanks it's working now

There is another problem with some games like Call of Duty Advanced Warfare


    On Saturday, March 2, 2024 at 04:13:23 AM EST, idlesauce ***@***.***> wrote:  
 
 


I think the issue was with the number of dlcs, not that it was different types, but regardless the latest version will probably work.

**Comment by idlesauce** [comment]
Yeah there are a few games that's main executable isn't the eboot.bin, in this case you have to patch default.elf and default_mp.elf

**Comment by Speed0780** [comment]
Thank you, the issue has been fixed

but There is another problem
![1](https://github.com/idlesauce/ps4-eboot-dlc-patcher/assets/160460604/7de62523-fb8f-4dde-a530-3f8bca915c6c)

**Comment by idlesauce** [comment]
Give the new version a shot, it should work
