### ISSUE TITLE
Getting an error of "Sanity check failed: codeScanEndReal Addr < codeScanStartReal Addr"

### ISSUE THREAD

**Issue by Saigaiii** [idlesauce/ps4-eboot-dlc-patcher#7]
![ps4 eboot dlc patcher error codeScanEndRealAddr](https://github.com/idlesauce/ps4-eboot-dlc-patcher/assets/112516856/7ef4aff7-670c-49da-ad70-f07a46901995)

Not sure what can be causing this. Trying to patch MHW iceborne master edition eboot.elf file (decrytped from eboot.bin) with one dlc in the same folder.

**Comment by Saigaiii** [comment]
I should also mention that I get this error as well, but I assume this is due to the limitations mentioned on the homepage of the tool.
![Ps4 eboot patcher dlc error](https://github.com/idlesauce/ps4-eboot-dlc-patcher/assets/112516856/0e7833d2-21f8-4cfc-a50b-3cdaac9b1035)

**Comment by idlesauce** [comment]
> ![ps4 eboot dlc patcher error codeScanEndRealAddr](https://private-user-images.githubusercontent.com/112516856/322116171-7ef4aff7-670c-49da-ad70-f07a46901995.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTk5NDksIm5iZiI6MTcxMjk1OTY0OSwicGF0aCI6Ii8xMTI1MTY4NTYvMzIyMTE2MTcxLTdlZjRhZmY3LTY3MGMtNDlkYS1hZDcwLWYwN2E0NjkwMTk5NS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMjIwNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODI1ZDVlNDE0OGJkMjYwNmJmM2YxZmVmMjZiOTk2NjAzMDEyNTZlYTJmMjQwNzZkMjVkNThkYjBkMzE1YWMzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0BCn63ABSj9N9K93tSy4-e_k26KPHH2Aw9fT4faAvVg)
> 
> Not sure what can be causing this. Trying to patch MHW iceborne master edition eboot.elf file (decrytped from eboot.bin) with one dlc in the same folder.

The dev branch should have a fix for this, you can grab builds for it from the actions tab, here is the latest win x64 binary as of now: [https://github.com/idlesauce/ps4-eboot-dlc-patcher/actions/runs/8620900803/artifacts/1398966775](https://github.com/idlesauce/ps4-eboot-dlc-patcher/actions/runs/8620900803/artifacts/1398966775 )
As for wo long, yeah, very likely it just uses entitlement access but i havent looked at this game specifically.

**Comment by Saigaiii** [comment]
> > ![ps4 eboot dlc patcher error codeScanEndRealAddr](https://private-user-images.githubusercontent.com/112516856/322116171-7ef4aff7-670c-49da-ad70-f07a46901995.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTk5NDksIm5iZiI6MTcxMjk1OTY0OSwicGF0aCI6Ii8xMTI1MTY4NTYvMzIyMTE2MTcxLTdlZjRhZmY3LTY3MGMtNDlkYS1hZDcwLWYwN2E0NjkwMTk5NS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMjIwNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODI1ZDVlNDE0OGJkMjYwNmJmM2YxZmVmMjZiOTk2NjAzMDEyNTZlYTJmMjQwNzZkMjVkNThkYjBkMzE1YWMzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0BCn63ABSj9N9K93tSy4-e_k26KPHH2Aw9fT4faAvVg)
> > Not sure what can be causing this. Trying to patch MHW iceborne master edition eboot.elf file (decrytped from eboot.bin) with one dlc in the same folder.
> 
> The dev branch should have a fix for this, you can grab builds for it from the actions tab, here is the latest win x64 binary as of now: https://github.com/idlesauce/ps4-eboot-dlc-patcher/actions/runs/8620900803/artifacts/1398966775 As for wo long, yeah, very likely it just uses entitlement access but i havent looked at this game specifically.

Yup the dev branch version fixed it for me. Thank you!
