### ISSUE TITLE
Assassins Creed Valhalla Patch Dlc Fail 

### ISSUE THREAD

**Issue by Hyndrid** [idlesauce/ps4-eboot-dlc-patcher#8]
![20240413_202531](https://github.com/idlesauce/ps4-eboot-dlc-patcher/assets/165535732/fde7b894-3073-4e2f-b464-dfe62e42000c)

**Comment by idlesauce** [comment]
Its the path, remove any [ ], ill fix this for the next release

**Comment by Hyndrid** [comment]
Nice thanks you working great
